### model
model_name_or_path: rdesc/Qwen2.5-VL_waymo_multistep_covla_pretraining_10400
image_max_pixels: 262144
video_max_pixels: 16384
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: full
freeze_vision_tower: true  # choices: [true, false]
freeze_multi_modal_projector: false  # choices: [true, false]
# train_mm_proj_only: false  # choices: [true, false]
deepspeed: examples/deepspeed/ds_z2_config.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]

### dataset
dataset: full_cot_navsim
template: qwen2_vl
cutoff_len: 131072
max_samples: 10000000
overwrite_cache: false
preprocessing_num_workers: 128
dataloader_num_workers: 32
tokenized_path: /home/jovyan/workspace/saves/dataset/full_cot_navsim

### output
output_dir: /home/jovyan/workspace/saves/qwen2_5_vl-3b/full/qwen2_5vl_full_sft_navsim_cot_poutine_base_bs32
logging_steps: 10
save_strategy: epoch
# save_steps: 200
save_total_limit: 2
save_only_model: false
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 4
learning_rate: 1.0e-5
num_train_epochs: 2.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

# wandb
report_to: wandb
run_name: qwen2_5vl_full_sft_navsim_cot_poutine_base_bs32
